# Example configuration file for Televoica Robot
# Save this as config.yaml and use with: televoica bot --config config.yaml

# Enable Telegram bot mode
telegram_bot: true

# Logging level (DEBUG, INFO, WARNING, ERROR)
log_level: INFO

# Temporary directory for storing downloaded files
temp_dir: /tmp/televoica

# Televoica provider configuration
stt_provider: whisper  # Options: whisper, google_cloud

# Whisper-specific settings
whisper_model: base  # Options: tiny, base, small, medium, large
whisper_device: cpu  # Options: cpu, cuda
whisper_language: null  # Optional: en, ar, es, fr, etc. (null = auto-detect)

# Google Cloud Televoica settings (if using google_cloud provider)
# google_credentials_path: /path/to/credentials.json
# google_language_code: en-US

# Telegram bot settings
# Note: Set TELEGRAM_BOT_TOKEN environment variable with your bot token
telegram_allowed_users: []  # Empty list = allow all users. Or specify user IDs: [123456789, 987654321]
telegram_max_file_size_mb: 20
